AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyCustomRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'  # Change this to whatever service you want to trust
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: MyRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::mumbai-replica-1/*'  # Replace with your S3 bucket ARN
                  - 'arn:aws:s3:::mumbai-replica-1'  # Replace with your S3 bucket ARN
                  
        - PolicyName: InstnacePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ec2:*'
                  - 'rds:Describe*'
                  - 'rds:ListTagsForResource'
                Resource:
                  - '*'  # Replace with your S3 bucket ARN
                  
        - PolicyName: DenyInstnacePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Deny'
                Action:
                  - 'ec2:TerminateInstances'
                Resource:
                  - '*'  # Replace with your S3 bucket ARN


Outputs:
  RoleName:
    Description: 'IAM Role Name'
    Value: !Ref MyIAMRole
  RoleArn:
    Description: 'IAM Role ARN'
    Value: !GetAtt MyIAMRole.Arn
