# create_pod.yml
- name: Create a Pod in Kubernetes
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Create pod
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: my-nginx-pod
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
