---
- name: Create an S3 bucket with versioning enabled
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    s3_bucket_name: "my-versioned-jenkins"  # Change this to a unique name
    s3_region: "us-east-1"

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        state: present
        region: "{{ s3_region }}"
      register: s3_create_result

    - name: Enable versioning on the S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket_name }}"
        versioning: yes
        state: present
        region: "{{ s3_region }}"
